CREATE DATABASE LOJADEROUPAS;

USE LOJADEROUPAS;

CREATE TABLE CLIENTE (
CODCLIENTE INT (10) NOT NULL PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR (50) NOT NULL,
CPF VARCHAR (11) UNIQUE NOT NULL,
SEXO VARCHAR (1) NOT NULL,
DATANASCIMENTO VARCHAR (10) NOT NULL,
TELEFONE INT (12) NOT NULL,
EMAIL VARCHAR (50) UNIQUE NOT NULL,
CEP VARCHAR (9) NOT NULL,
ENDERECO VARCHAR (100) NOT NULL,
BAIRRO VARCHAR (20) NOT NULL,
NUMERO INT (5) NOT NULL,
COMPLEMENTO VARCHAR (30),
CIDADE VARCHAR (30) NOT NULL,
ESTADO VARCHAR (20) NOT NULL
);


CREATE TABLE FUNCIONARIO (
CODFUNCIONARIO INT (10) NOT NULL PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR (50) NOT NULL,
CPF VARCHAR (11) UNIQUE NOT NULL,
SEXO VARCHAR (1) NOT NULL,
DATANASCIMENTO VARCHAR (10) NOT NULL,
TELEFONE INT (12) NOT NULL,
EMAIL VARCHAR (50) UNIQUE NOT NULL,
CEP VARCHAR (9) NOT NULL,
ENDERECO VARCHAR (100) NOT NULL,
BAIRRO VARCHAR (20) NOT NULL,
NUMERO INT (5) NOT NULL,
COMPLEMENTO VARCHAR (30),
CIDADE VARCHAR (30) NOT NULL,
ESTADO VARCHAR (20) NOT NULL,
LOGIN VARCHAR (50) NOT NULL,
SENHA VARCHAR(20) NOT NULL
);


CREATE TABLE GERENTE (
CODGERENTE INT (10) NOT NULL PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR (50) NOT NULL,
CPF VARCHAR (11) UNIQUE NOT NULL,
SEXO VARCHAR (1) NOT NULL,
DATANASCIMENTO VARCHAR (10) NOT NULL,
TELEFONE INT (12) NOT NULL,
EMAIL VARCHAR (50) UNIQUE NOT NULL,
CEP VARCHAR (9) NOT NULL,
ENDERECO VARCHAR (100) NOT NULL,
BAIRRO VARCHAR (20) NOT NULL,
NUMERO INT (5) NOT NULL,
COMPLEMENTO VARCHAR (30),
CIDADE VARCHAR (30) NOT NULL,
ESTADO VARCHAR (20) NOT NULL,
LOGIN VARCHAR (50) NOT NULL,
SENHA VARCHAR(20) NOT NULL
);


CREATE TABLE FILIAL (
CODFILIAL INT (10) NOT NULL,
ESTADO VARCHAR (20) NOT NULL
);

ALTER TABLE FILIAL
ADD CONSTRAINT PK_CODFILIAL_FILIAL PRIMARY KEY (CODFILIAL);

CREATE TABLE PRODUTO (
COD_FILIAL INT (10) NOT NULL,
CODPRODUTO INT (10) NOT NULL,
NOME VARCHAR (100) NOT NULL,
TIPO VARCHAR (30) NOT NULL,
QUANTIDADE INT (10) NOT NULL,
VALOR_COMPRA NUMERIC (10,2) NOT NULL,
VALOR_VENDA NUMERIC (10,2) NOT NULL
);

ALTER TABLE PRODUTO
ADD CONSTRAINT PK_CODPRODUTO_PRODUTO PRIMARY KEY (CODPRODUTO),
ADD CONSTRAINT FK_FILIAL_PRODUTO FOREIGN KEY (COD_FILIAL) REFERENCES FILIAL (CODFILIAL);


CREATE TABLE ESTOQUE (
COD_PRODUTO INT (10) NOT NULL,
QUANTIDADE INT (10) NOT NULL
);

ALTER TABLE ESTOQUE
ADD CONSTRAINT FK_PRODUTO_ESTOQUE FOREIGN KEY (COD_PRODUTO) REFERENCES PRODUTO(CODPRODUTO);


CREATE TABLE VENDA (
CODVENDA INT (10) NOT NULL PRIMARY KEY AUTO_INCREMENT,
DATA_VENDA VARCHAR (10) NOT NULL,
COD_CLIENTE INT (10) NOT NULL,
COD_PRODUTO INT (10) NOT NULL,
COD_FILIAL INT (10) NOT NULL,
QUANTIDADE INT (10) NOT NULL,
DESCONTO NUMERIC (10,2),
VALOR_TOTAL NUMERIC (10,2) NOT NULL
);


ALTER TABLE VENDA
ADD CONSTRAINT FK_CLIENTE_VENDA FOREIGN KEY (COD_CLIENTE) REFERENCES CLIENTE (CODCLIENTE),
ADD CONSTRAINT FK_PRODUTO_VENDA FOREIGN KEY (COD_PRODUTO) REFERENCES PRODUTO (CODPRODUTO),
ADD CONSTRAINT FK_FILIAL_VENDA FOREIGN KEY (COD_FILIAL) REFERENCES FILIAL (CODFILIAL);

CREATE TABLE VENDA_HAS_PRODUTO (
COD_VENDA INT (10) NOT NULL,
COD_CLIENTE INT (10) NOT NULL,
COD_PRODUTO INT (10) NOT NULL,
COD_FILIAL INT (10) NOT NULL
);

ALTER TABLE VENDA_HAS_PRODUTO
ADD CONSTRAINT FK_VENDA_AUXILIARVENDA FOREIGN KEY (COD_VENDA) REFERENCES VENDA (CODVENDA),
ADD CONSTRAINT FK_CLIENTE_AUXILIARVENDA FOREIGN KEY (COD_CLIENTE) REFERENCES CLIENTE (CODCLIENTE),
ADD CONSTRAINT FK_PRODUTO_AUXILIARVENDA FOREIGN KEY (COD_PRODUTO) REFERENCES PRODUTO (CODPRODUTO),
ADD CONSTRAINT FK_FILIAL_AUXILIARVENDA FOREIGN KEY (COD_FILIAL) REFERENCES FILIAL (CODFILIAL);





